version: '3'
services:
  flume:
    build: ./flume
    depends_on:
      - spark
  generator:
    build: ./generator
    depends_on: 
      - flume 
  mysql:
    build: ./mysql
  monitor:
    build: ./monitor
    depends_on:
      - mysql
  spark:
    build: ./spark-streaming
    depends_on:
      - mysql
